### ISSUE TITLE
Make the psychometric function and its inverse a first class object

### ISSUE THREAD

**Issue by pberkes** [wichmann-lab/python-psignifit#102]
At the moment, we have normalized sigmoids, and the transformations with gamma and lambda are done ad hoc around the code. 

For the tests, we defined a `psychometric` function in `test_recover_param`. This function, and its inverse, should live somewhere accessible and used across the code.

**Comment by otizonaizit** [comment]
The psychometric function object was made first class in #118
The inverse is still missing

**Comment by pberkes** [comment]
Closing as fixed
