### ISSUE TITLE
width alpha parameter effectively ignored

### ISSUE THREAD

**Issue by otizonaizit** [wichmann-lab/python-psignifit#11]
Shouldn't this line: 
https://github.com/wichmann-lab/python-psignifit/blob/9948db5c354cd811cff62b9fc00e5ea2c623a255/psignifit/getSigmoidHandle.py#L22

actually say:

```python
if not hasattr(options, 'widthalpha'):
```
Right now `getSigmoidHandle` ignores the parameter and overwrites it to be `0.05`.

**Comment by HeikoSchuett** [comment]
Yes, it should have the not.
It might be good to add a test that the widthalpha actually changes the result of the fitting & maybe in the right direction

**Comment by HeikoSchuett** [comment]
I finally put this into the master.
