### ISSUE TITLE
Remove option to set stimulus range manually

### ISSUE THREAD

**Issue by dekuenstle** [wichmann-lab/python-psignifit#112]
Currently, we plan to remove [this](https://github.com/wichmann-lab/psignifit/blob/dc8098f2d4da25632ce74db06dffddd3618798da/psignifit.m#L140) option from the python version.
Apparently it is only used if one tries to set the stimulus range independent from data.
We think it causes trouble in the tests and is almost never used. 

@HeikoSchuett any objections?

**Comment by otizonaizit** [comment]
The current solution seems to make sense and after discussion with everyone we decided to keep it that way.
