### ISSUE TITLE
option setBordersType ignored/unused

### ISSUE THREAD

**Issue by otizonaizit** [wichmann-lab/python-psignifit#12]
What is `options['setBordersType']` used for?
In [demo_002](https://github.com/wichmann-lab/python-psignifit/blob/master/psignifit/demos/demo_002.py) it says

> The method to set the outer borders of the grid. You find it's use in `setBorders`. defaults to reasonable estimates for the threshold and width parameter
 
But then the function `setBorders` in [borders.py](https://github.com/wichmann-lab/python-psignifit/blob/master/psignifit/borders.py) does not use the option at all… Note that the matlab version does the same thing, i.e. the option is ignored/unused.

Can we get rid of it completely?

**Comment by HeikoSchuett** [comment]
We can indeed drop this entirely. 

Originally I tried other ways to set the borders of the grid including some surrounds of the MAP estimate etc. and this option allowed choosing among the different methods. 
I never found any stable improvement over the method psignifit uses now though and thus did not include any of this in any release.

**Comment by HeikoSchuett** [comment]
Removed the references now
