### ISSUE TITLE
conftest.py should be in `tests` folder

### ISSUE THREAD

**Issue by pberkes** [wichmann-lab/python-psignifit#128]
otherwise tests cannot be run in the installed package

**Comment by otizonaizit** [comment]
I looked into it and it seems that adding a custom CLI option for pytest, as we do in `conftest.py` can not be done unless the file is in the top-level directory... I don't think there's an easy way out...

**Comment by lschwetlick** [comment]
I also just tried to research this, and didnt find a solution.

On the other hand, does anyone pip install a package, and then goes to the 20 levels of indirection within their environment to find it, and then runs the tests there?

I would have thought someone who wants to run the tests would, anyway, have cloned the git repo...

**Comment by pberkes** [comment]
we decided to not move the tests out of the package, and not distribute them
