### ISSUE TITLE
`biasAna` ignores options

### ISSUE THREAD

**Issue by toddrjen** [wichmann-lab/python-psignifit#13]
The `biasAna` function allows an `options` argument, but this argument is immediately overwritten so it has no effect.  The MATLAB version does the same thing.

**Comment by HeikoSchuett** [comment]
Hi toddrjen,
sorry it took me so long to react. I forgot to answer.
The biasAna function cannot ignore the options entirely. At least which sigmoid is to be fit is still required. 
In the Matlab version I now added a test whether you set some options before setting them. Nonetheless the settings we set in the function are quite necessary to make the function behave as expected. Thus you typically should not set them.

**Comment by toddrjen** [comment]
In the [first code line](https://github.com/wichmann-lab/python-psignifit/blob/9948db5c354cd811cff62b9fc00e5ea2c623a255/psignifit/psignifit.py#L778) if the function, you have `options = dict()`.  This overwrites the `options` variable you set with an empty dict.

**Comment by HeikoSchuett** [comment]
Well, you are right there. I fixed this such that it does not overwrite the options any more. I used the deepcopy anyway here for consistency with the other code and to be robust if we add a change in place at some point. 
Thank you for pointing this out!

I think we will add a proper fix once all internal restructuring is done.
