### ISSUE TITLE
Sometimes the confidence interval's upper bound is lower than the estimate

### ISSUE THREAD

**Issue by lschwetlick** [wichmann-lab/python-psignifit#143]
See the title.

See here for an example:
https://gist.github.com/lschwetlick/b6168ed60668076e0d0c510811c40fd3

This is only the case if you use the `percentiles` CI method.

**Comment by otizonaizit** [comment]
@FelixWichmann : do you think this statistically possible and due to the imprecision of estimating the confidence intervals using the percentile method or is it the sign of a bug?

@guillermoaguilar : could you test if matlab shows he same effect using the same data?

**Comment by FelixWichmann** [comment]
> @FelixWichmann : do you think this statistically possible and due to the imprecision of estimating the confidence intervals using the percentile method or is it the sign of a bug?
To me rather a sign of a bug, I'm afraid.

> @guillermoaguilar : could you test if matlab shows he same effect using the same data?
Indeed -- what does MATLAB show?

Sorry but I won't be able to look into psignifit issues until Friday late afternoon/weekend.
Please let me know if the problem persists.

Cheers, Felix

**Comment by guillermoaguilar** [comment]
I ran the same data in MATLAB, it does give different results, the estimate is inside the CI. The MATLAB version estimates a much shallower function, and if you look at the marginals they are indeed different between the two implementations.

Here the plots from MATLAB and python (in that order) for the psychometric function:

![bug_ci_matlab1](https://github.com/user-attachments/assets/a31df248-4818-47b5-93d7-f6b074782ba7)
![bugci_python1](https://github.com/user-attachments/assets/fa9f8934-4c2f-4f26-8549-6c7aeb32b97e)

the marginal for the threshold:

![bug_ci_matlab2](https://github.com/user-attachments/assets/c0d3322a-0ebc-4ea1-8422-84b59875ff7d)
![bugci_python2](https://github.com/user-attachments/assets/343ad618-ff84-4e5f-92d0-53d226c7d75c)

the marginal for the width:

![bugci_python3](https://github.com/user-attachments/assets/785a25d6-7c02-47d1-88dc-4b12b919165f)
![bug_ci_matlab3](https://github.com/user-attachments/assets/c6c237d7-72ae-4161-a7a7-5f3ea9d74e45)


Now I have to say there are many things that make this a very special case
- very little data, just four x-values. Data matrix is: `data =  [[14. 14. 30.],  [24.  8. 30.],  [34. 28. 30.],  [44. 29. 30.]]`
- The experiment type is 'Yes No" but we fix gamma to 0.5.  AFAIK for Yes/No the usual user case would be to leave all parameters free. And as you see in the data, the datapoints suggest a gamma of around 0.3. Maybe forcing the value to something unlikely make things behave weird somehow?

And another thought: in this example only the 68% CI does not include the estimate, for 95% and 90% CI it does. It is expected that a 68%CI does not include the estimate in  32% of the time, no? That's the definition of the CI.

**Comment by guillermoaguilar** [comment]
What do you think @FelixWichmann?

**Comment by guillermoaguilar** [comment]
> And another thought: in this example only the 68% CI does not include the estimate, for 95% and 90% CI it does. It is expected that a 68%CI does not include the estimate in 32% of the time, no? From the definition of the CI.

Nevermind this, I had a Denkfehler. For coverage we calculate how many times the *ground truth* value is inside the CI. The estimate should be always inside the CI.

**Comment by HeikoSchuett** [comment]
Hi! 
Thank you all for taking time to make python psygnifit happen finally!
On this example: In principle estimates can be outside the CI, as we use MAP estimates by default. That happens relatively often for lapse rates actually, where the MAP can be 0 and percentile CIs never include that value. 

Here, the issue I see in the plots seems to be a substantially different setting of the width prior. The MATLAB prior categorically excludes most of the posterior according to python. That is what leads to the much shallower curve in MATLAB and the discrepancy of results.

**Comment by pberkes** [comment]
@guillermoaguilar  in Lisa's code, the optional `stimulus_range` parameter is set, and that sends the code down a different path when defining the minimum width (psignifit.py:72), and therefore the width prior.
Con you please check if that parameter is set (or unsed) in both Python and Matlab for the code you used to generate the screenshots?

**Comment by guillermoaguilar** [comment]
Yes exactly @pberkes , that was the reason for the major source of discrepancies (plus the x-axis range thing I had to solve first, see #150)

There is still very minor discrepancies in the marginals. Here the comparison where I made sure options/configuration is exactly the same.

Point estimates

MATLAB
threshold:   31.9782
width:    4.8809
lambda:   0.0256
eta:   0.0000

python
{'gamma': np.float64(0.5),
 'eta': np.float64(1.0000898557551566e-08),
 'lambda': np.float64(0.02564108011093528),
 'threshold': np.float64(32.86621036378611),
 'width': np.float64(2.737067525037828)}

-> So slight difference in width. 

Psychometric function:
MATLAB
![matlab_psych_fx](https://github.com/user-attachments/assets/eda8ab9b-96e2-4943-bf61-a1571e5b9659)

Python
![python_psych_fx](https://github.com/user-attachments/assets/865b979f-6e94-4e12-b8a2-650bf393e695)

-> python is slightly steeper


Marginal for threshold

![matlab_threshold](https://github.com/user-attachments/assets/15b2402f-0ca8-459f-a258-f85673cd40ad)

 
![python_threshold](https://github.com/user-attachments/assets/b90bb7be-d9e5-4fc3-9369-d7d5e7acba2a)


for width

![matlab_width](https://github.com/user-attachments/assets/3e8dee09-9bbd-4722-9cc0-73a0ef88015b)


![python_width](https://github.com/user-attachments/assets/5598b81a-854a-47c2-ae49-58eca11f961b)


for Lambda

![matlab_lambda](https://github.com/user-attachments/assets/26461cf5-e29e-41ad-afea-c5778c3eaec1)

![python_lambda](https://github.com/user-attachments/assets/b5a1ccec-e93b-4813-87d6-0154a030d766)


for Eta
![matlab_eta](https://github.com/user-attachments/assets/2dfbf346-a5d9-496d-a23b-114a71f6817d)

![python_eta](https://github.com/user-attachments/assets/4d3a1746-2bec-45b7-9b5e-e507fece09aa)



So these are very very  very close but not quite exactly the same. 

While debugging all this I notice that usually the discrepancy is on the *first* datapoint, on the left, particularly for lambda and eta where it matters most. 
I don't know if a numerical problem is happening during the marginalization... ?

**Comment by pberkes** [comment]
Tiziano and I found a off-by-one error when computing the right bound of the smaller grid for optimization. Could it be an index that is not included? do you remember at which point in the code there is a discrepancy?

**Comment by guillermoaguilar** [comment]
I think it's here: 

https://github.com/wichmann-lab/python-psignifit/blame/516467e06180bf9cb4f0530f31b09104b47ce2c4/psignifit/_posterior.py#L43

This weights calculation seems different than in the Matlab version, how the boundaries are handled. 
Here in python the two extreme points are halved.

In MATLAB it doesn't seem to be the case, although I don't fully understand the code:

https://github.com/wichmann-lab/psignifit/blob/dc8098f2d4da25632ce74db06dffddd3618798da/private/getWeights.m#L23

it would be consistent with that I've observed inconsistencies with the marginals that are skewed to the left, lambda, eta, and sometimes the width in cases.  I see it as the first point being always more or less half lower. The difference in the right point we don't see it because it's usually around zero.

Can it be?

**Comment by otizonaizit** [comment]
... hmm, so the Python code around the lines you posted is a straightforward implementation of the [trapezoidal rule](https://en.wikipedia.org/wiki/Trapezoidal_rule) for numerical integration. The weights at the boundaries of the integration interval are half of those within the interval.

The matlab code is unintelligible for me, but it looks like the matlab version the boundaries are not treated specially. I would say that the matlab code is mistaken :-P

On the other hand, all of this only really matters for the extreme cases where there are just a few data points, no?

**Comment by guillermoaguilar** [comment]
Yep. I just talked to Felix about this.

He thinks these small differences on the borders shouldn't make a big difference in the estimate and CI, so it would be better now to actually just run the tests / simulations against MATLAB and see if there's any residual difference. In other words, to replicate [this figure done before the refactoring](https://psignifit.readthedocs.io/en/latest/test_MATLAB_version.html). This would be a new issue, related to PR #66. 


Another thing is that the steeper function behavior, which also leads to estimate outside the CI,  happens when we set up manually the variable `stimulus_range`. Manually setting it has the consequence of [changing how the minimum for the prior width is calculated](https://github.com/wichmann-lab/python-psignifit/blob/516467e06180bf9cb4f0530f31b09104b47ce2c4/psignifit/psignifit.py#L75C1-L76C80). This also happens in MATLAB.

We both think that the normal end user shouldn't touch this variable, and they should let psignifit decide on the reasonable parameters. The documentation in MATLAB does not mention this possibility of manual change either. So all in all we should not do that, either in tests or documentation. The code from @lschwetlick that opened this issue is then a case that shouldn't normally happen.

**Comment by otizonaizit** [comment]
> He thinks these small differences on the borders shouldn't make a big difference in the estimate and CI, so it would be better now to actually just run the tests / simulations against MATLAB and see if there's any residual difference. In other words, to replicate [this figure done before the refactoring](https://psignifit.readthedocs.io/en/latest/test_MATLAB_version.html). This would be a new issue, related to PR #66.

@guillermoaguilar @FelixWichmann : where is the code used to generate that figure? It is very straightforward to see how far we are from replicating it if we get access to the code.

**Comment by otizonaizit** [comment]
@guillermoaguilar : can you post on a gist the Python and the Matlab code that you used to generate the plots here https://github.com/wichmann-lab/python-psignifit/issues/143#issuecomment-2400581415 ?

**Comment by guillermoaguilar** [comment]
OK here.

MATLAB code: https://gist.github.com/guillermoaguilar/e0adf501fc4bf25db92b4d3ab5119ce8

Python code:  https://gist.github.com/guillermoaguilar/12942816c4643499ad6f224076fae5e5

**Comment by pberkes** [comment]
For the record, if we remove the `stimulus_range` for Python, we get a similar result to what initially reported for Matlab:
<img width="605" alt="image" src="https://github.com/user-attachments/assets/1d52b018-08e7-4407-98d4-bf9e7b4462e8">
<img width="1036" alt="image" src="https://github.com/user-attachments/assets/6d902be5-35f1-4b29-b6c4-73aa7f5a3c26">
<img width="304" alt="image" src="https://github.com/user-attachments/assets/cccc89f9-f479-488b-ba39-533d8e36e3d2">

**Comment by pberkes** [comment]
Finally, when the stimulus range is set, the minimum width is set in Matlab as something related to the minimum precision error, i.e. extremely small. I had changed it to something more meaningful (1/100 of the stimulus range) here: https://github.com/wichmann-lab/python-psignifit/pull/110/files#diff-115fcf9d81c57ae4d84423abd08d2eda0777cbce71215690f9c6e8218e37be89L76
The reason for the change is that some sigmoids do a calculation related to 1/width, and when the minimum is something like 10^15, that gives warnings and numerical errors.

Putting it back to the Matlab definition (i.e. undoing the change linked above) gives estimates similar to the Matlab ones:
<img width="600" alt="image" src="https://github.com/user-attachments/assets/56231f25-eef1-460b-aef9-6e79864a42fd">
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/28d0f3a7-73c0-4888-82d2-16967e0f43b7">
<img width="299" alt="image" src="https://github.com/user-attachments/assets/d049cac7-9f2d-4df5-8b88-03a4a642d935">

**Comment by pberkes** [comment]
Given these, results, I personally think that 1) the confidence interval being outside the MAP estimate has been explained as mathematically possible in some realistic cases; 2) there is no significant difference between Matlab and Python for the example in this issue. 

I suggest we close this ticket as a non-issue

**Comment by otizonaizit** [comment]
Thank you @pberkes ! I agree with your assessment. We can close the issue in my opinion. We won't forget to remove the user-facing `stimulus_range` option, because its removal is tracked in https://github.com/wichmann-lab/python-psignifit/issues/145#issuecomment-2404173574 . The only thing I am wondering about is if it makes sense to set `min_width` to something smaller than `0.01*stimulus_range`. Given that MATLAB is using `10^(-16)`, couldn't we take something smaller but not as crazy? Something like `10^(-5)*stimulus_range` may be good. It won't make a difference in the majority of the cases, but would make the divergence to the MATLAB results a bit smaller and may help the efforts going on in #66 ? What do you think @pberkes ?

@guillermoaguilar : can you close this issue after you have reviewed it and if you agree with @pberkes assessment?

**Comment by pberkes** [comment]
@otizonaizit when the stimulus range is not defined (the path that would be taken if we remove the option), the minimum width is `width_min = np.diff(np.unique(levels)).min()`, i.e., the minimum distance between stimulus levels. The idea is that that is the width shouldn't be smaller than the smallest stimulus distance that we can distinguish in the data.

The formula I used is equivalent to assume 100 equally spaced stimulus levels. The library normally assumes max 25 levels

**Comment by otizonaizit** [comment]
Cool, thanks for the explanation :) This means that the problem solves 
itself as soon as we remove the option. Nice ;)

14 Oct 2024 16:27:46 Pietro Berkes ***@***.***>:

**Comment by guillermoaguilar** [comment]
> The idea is that that is the width shouldn't be smaller than the smallest stimulus distance that we can distinguish in the data.

that's exactly what Felix & Heiko set up, in a way formalizing the idea that the user/experimenter is placing the stimulus values in a reasonable way

So yes I completely agree. Closing...

**Comment by pberkes** [comment]
One more element to confirm what we said about the MAP estimate being outside the confidence interval. If we use the "mean" estimate (PR #161) , the estimate is correctly in the middle.

"MAP" estimate
<img width="627" alt="image" src="https://github.com/user-attachments/assets/09b1feb8-9936-46db-be5f-62b246c667fc">

"mean" estimate
<img width="608" alt="image" src="https://github.com/user-attachments/assets/9d9d47e7-2a16-45c6-8d25-3820ab36d02d">
