### ISSUE TITLE
Unused options in _configuration.py

### ISSUE THREAD

**Issue by lschwetlick** [wichmann-lab/python-psignifit#145]
While writing the docs for the options dict I found that some options in the configs are never used:

- fast_optim
- instant_plot
- grid_set_type

can they be removed?

**Comment by otizonaizit** [comment]
Related to #92 and #142

**Comment by guillermoaguilar** [comment]
add to this list

- move_bounds

**Comment by otizonaizit** [comment]
We have to get rid also of `stimulus_range`, see discussion in https://github.com/wichmann-lab/python-psignifit/issues/143
