### ISSUE TITLE
setup.py fails in python 2.7

### ISSUE THREAD

**Issue by HeikoSchuett** [wichmann-lab/python-psignifit#15]
This is the error message in a clean conda environment (numpy,scipy,matplotlib, python 2.7.15)

```
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    metadata = dict((var, parse_keyword('__%s__'%var)) for var in metadata_vars)
  File "setup.py", line 30, in <genexpr>
    metadata = dict((var, parse_keyword('__%s__'%var)) for var in metadata_vars)
  File "setup.py", line 16, in parse_keyword
    with open(os.path.join(CWD, INITFILE), encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by otizonaizit** [comment]
Yes, that's expected. python-psifgnifit supports python 3 only. That makes sense, if you consider that the project has no legacy to support and that all 3, numpy, scipy, and matplotlib, are not supporting python 2 in their last versions anymore ;)

See for example: https://www.numpy.org/neps/nep-0014-dropping-python2.7-proposal.html , https://matplotlib.org/index.html (blue box on the right), https://mail.python.org/pipermail/scipy-dev/2018-November/023181.html

and the same is happening for scikit-learn, scikit-image, etc...

**Comment by HeikoSchuett** [comment]
I am closing this now. Will add a comment to the documentation that we stop supporting 2.7 officially.
