### ISSUE TITLE
Bugs in prior plotting - selected sigmoids

### ISSUE THREAD

**Issue by dekuenstle** [wichmann-lab/python-psignifit#151]
The prior plotting function should add dots for the min, max, quantiles, and point estimate. However, they appear not at the right positions in the plot. 

@guillermoaguilar Could you please add the screenshots?

**Comment by guillermoaguilar** [comment]
MATLAB priors:

![Screenshot from 2024-10-07 12-22-25](https://github.com/user-attachments/assets/7382421a-a313-48bf-a123-e188f8411444)

Python priors:
![Screenshot from 2024-10-07 12-22-44](https://github.com/user-attachments/assets/53b9c9b8-5d0e-4d75-9acd-93fd7e4f2053)

Width prior is different, particularly on the left side. 

Dots are also different. Black is the point estimate, red and blue the quartiles. Green and yellow are the same, they are the min and max of the range of possible parameter values.

**Comment by HeikoSchuett** [comment]
The black dot in the prior seems to be still off in #154 . It should be at the prior mean but is clearly not. So the placement is not right yet.

**Comment by pberkes** [comment]
@HeikoSchuett the black dot is not the mean but the MAP estimate, it looks good from the marginals.

**Comment by pberkes** [comment]
@HeikoSchuett it's the same in Matlab: https://github.com/wichmann-lab/psignifit/blob/master/plotPrior.m#L97

**Comment by guillermoaguilar** [comment]
So actually plot_prior still needs correction after I talked to Felix last week (sorry I didnt post it before, I was busy with the docs)

He told me: 
the points in this plot_priors are supposed to show the range of likely and not likely sigmoids. 

- The black should be the estimate, so you show where you estimate lands in the prior (showing it's a flat part of the prior and not somewhere else completely crazy that would bias the estimate). I think this is correctly implemented in python.
- the red and blue should be the 25% and 75% of the *sigmoid*, not the prior. The logic is to show that these two points  land also in a reasonable flat part of the prior. 
- the green and yellow are for the min and max of the prior, showing these sigmoids are crazy off and not at all likely. This is correctly implemented.

BUT if you look at the [paper](https://github.com/user-attachments/files/17393574/1-s2.0-S0042698916000390-main.pdf), Fig. 3, it says these are the 0, 25, 50, 75 and 100% quantiles of the *prior*.

So now I'm confused again.

@HeikoSchuett how should it be?

**Comment by pberkes** [comment]
@guillermoaguilar 
"the red and blue should be the 25% and 75% of the sigmoid, not the prior" -> the 25% and 75% of the MAP sigmoid?

**Comment by pberkes** [comment]
That would work for the threshold plot, but how can we plot the 25% and 75% of the sigmoid in the width or lambda plot?

**Comment by guillermoaguilar** [comment]
> That would work for the threshold plot, but how can we plot the 25% and 75% of the sigmoid in the width or lambda plot?

I don't know. Maybe I understood Felix wrong. Let's see what Heiko answers.

**Comment by pberkes** [comment]
In any case, as far as I can tell the current code is equivalent to the Matlab version

**Comment by pberkes** [comment]
@guillermoaguilar @HeikoSchuett  PR #154 has been merged... I believe the implementation is equivalent to the Matlab code. Can we close this issue, or are there more changes you'd like to do?

**Comment by guillermoaguilar** [comment]
There's only one residual difference.. on the black dot. The black dot over the lambda prior is not quite right. I'm trying to understand now why is this the case.

**Comment by guillermoaguilar** [comment]
This issue will be closed by #186
