### ISSUE TITLE
Get Standard Parameters

### ISSUE THREAD

**Issue by alexsbaldwin** [wichmann-lab/python-psignifit#160]
The documentation mentions this feature is not yet implemented:
https://psignifit.readthedocs.io/en/latest/how_to/How-to-Get-Standard-Parameters.html

Is this still correct? This function would be useful for a current project I am working on, so I will likely implement it in a forked repository.

**Comment by pberkes** [comment]
That's correct, it has not been implemented yet in Python

**Comment by guillermoaguilar** [comment]
I think this will be important to implement. Many people use the standard parameters for ex. for the Gaussian sigmoid.
