### ISSUE TITLE
Result.parameter_estimate 

### ISSUE THREAD

**Issue by guillermoaguilar** [wichmann-lab/python-psignifit#173]
`Result.parameter_estimate`  should point by default to 
`Result.parameters_estimate_MAP`

**Comment by otizonaizit** [comment]
#161 changed the interface. The new interface is `Result.get_parameters_estimate()`, which returns the estimate of the parameters using the method that is defined in the configuration. If the user does not change anything, the default method is `MAP` and the method `Result.get_parameters_estimate()` returns `Result.parameters_estimate_MAP`: see https://github.com/wichmann-lab/python-psignifit/blob/e9da3c7b4697876d48848bc220857cd1aed39d3d/psignifit/_result.py#L71

**Comment by guillermoaguilar** [comment]
Ok. PR #174 fixes that in the documentation. Dont want to have the basic documentation broken for so long

Still from the user perspective I find it strange that  you do `get_parameters_estimate()` to get the estimates but you do `result.confidence_intervals`  to get the CIs.  One is a method, the other just a dictionary.

**Comment by guillermoaguilar** [comment]
Closed by #174

**Comment by otizonaizit** [comment]
You have a point with the inconsistency. I personally prefer the attribute access too. That method can be converted to an attribute by defining it as a property. I can take care of that, so I re-opened the issue not to forget.
@pberkes : what do you think?

**Comment by pberkes** [comment]
the parameters estimate need to specify whether one wants the MAP or mean estimate, the confidence intervals are independent

**Comment by otizonaizit** [comment]
Yes, but I want the  parameters estimated by the default method in 99% of 
the cases. For the people that know what they are doing, using the 
attributes with the corresponding names is pretty easy already, no?

28 Nov 2024 18:03:10 Pietro Berkes ***@***.***>:

**Comment by guillermoaguilar** [comment]
Yes, 99% of the people want 'the default', because they know that the developers in the publication (Heiko, Felix, etc) already tested different options and they're providing the best. They trust it.

And also that's why I think I need to insist on this point, I think we *need* to have `parameter_estimate` back, that points by default MAP.  To anyone that have installed v.4.2  this is breaking their code.

**Comment by otizonaizit** [comment]
Yes, it's coming back. I need until Wednesday though :)

29 Nov 2024 15:13:03 Guillermo Aguilar ***@***.***>:
