### ISSUE TITLE
standard_parameters will fail when alpha==0

### ISSUE THREAD

**Issue by pberkes** [wichmann-lab/python-psignifit#175]
I forgot to test for the corner case / not unlikely case when alpha is exactly 0.0 .
The standard_parameters method will fail for those cases, because the rescaling will give inifinities and nans.

other stuff would have failed also before #169, for example in the Logistic sigmoid we had
`C = 2 * np.log(1 / self.alpha - 1) / width`
which is going to cause a division by zero.

**Comment by dekuenstle** [comment]
Along this line, we might consider validation for all (sigmoid) parameters. 

We can do this manually or use a data model like [pydantic](https://docs.pydantic.dev/latest/).

**Comment by otizonaizit** [comment]
closing as not-a-bug. See discussion in #177 for detail.
