### ISSUE TITLE
Error when trying to plot Weibull results

### ISSUE THREAD

**Issue by xteeven** [wichmann-lab/python-psignifit#18]
Hi everyone, I started using psignifit 4 a few days ago when I tried to plot a Weibull function, I get "AttributeError: This method only works with the ScalarFormatter.".

after several trials, I solved it adding:
`plt.gca().xaxis.set_major_formatter(ScalarFormatter())`

after:
`plt.ticklabel_format(style='sci',scilimits=(-2,4))`
in the plotPsych() Funtion wich is inside psigniplot.py.

let me know if this is a general issue or I am missing something.

**Comment by HeikoSchuett** [comment]
Hi! 
Thank you for finding this Problem! I just checked, could reproduce the problem and uploaded a version, which should fix this based on your solution. Could you download and check whether this is fixed?
best
Heiko
