### ISSUE TITLE
demos location 

### ISSUE THREAD

**Issue by guillermoaguilar** [wichmann-lab/python-psignifit#180]
The folder psignifit/demos has some demos that are now redundant with the jupyter book documentation in docs/ 
These are: 
- demo_001 to _006
- parameter_recovery_demo.ipynb  and
- plot_all_sigmoids.py

All these have been migrated to the markdown format and reorganized in docs/. 

Now the question is to whether delete these ones there in psignifit/demos or not. 

These get executed when the documentation is built. But the build does not raise errors during CI testing. The only way of checking is manually looking.

So it is confusing to have them in two places, but at the same time the documentation in docs/ can be broken and we dont notice, because tests still pass.
 
So I dont know, what do you all think?

**Comment by otizonaizit** [comment]
I just checked and it is possible to configure `jupyter-book` to exit with an error if one of the generated notebooks fails to execute:

```python
jupyter-book build --warningiserror docs/
```

so, we just need to add here: https://github.com/wichmann-lab/python-psignifit/blob/710f9f7db6992ece9f5aae9e5a096c6b562fb36f/.github/workflows/build-docs.yml#L38

**Comment by guillermoaguilar** [comment]
Ok that's good! I'll take care of it then
