### ISSUE TITLE
Not able to install toolbox 

### ISSUE THREAD

**Issue by Openbro** [wichmann-lab/python-psignifit#20]
Setup.py file says `No module named setuptools`

I tried installing setup tools as well but still, the same issue persists.

Please provide a solution.

**Comment by HeikoSchuett** [comment]
Can you provide the full error message please? Also: Did the install of setuptools work? Which Version of python are you using?

**Comment by Openbro** [comment]
here is the message post installing setuptools 

`Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools`


also, python version is 2.7.6

Do I need an upgrade??

I am not using  any vms.

**Comment by Openbro** [comment]
Also this :

`Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    metadata = dict((var, parse_keyword('__%s__'%var)) for var in metadata_vars)
  File "setup.py", line 30, in <genexpr>
    metadata = dict((var, parse_keyword('__%s__'%var)) for var in metadata_vars)
  File "setup.py", line 16, in parse_keyword
    with open(os.path.join(CWD, INITFILE), encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function`


I removed and reinstalled setuptools via pip and now I get these bunch of errors on installing setup.py

**Comment by otizonaizit** [comment]
psignifit only works with Python 3. You are getting this errors because you are trying to install it with Python 2. You'll need to upgrade your Python installation.
Also, note that Python 2 is going to be retired in January 2020: https://pythonclock.org/ ⟶ it is a good time to upgrade now! :-)

**Comment by Openbro** [comment]
I know about the deprecation notice about python3 but this is what I get when i use python3. 

Okay so here is the stuff with python3

Most significant part of the error message being `error: Could not find suitable distribution for Requirement.parse('pytest')`

`
reading manifest file 'psignifit.egg-info/SOURCES.txt'
writing manifest file 'psignifit.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/psignifit
copying build/lib/psignifit/borders.py -> build/bdist.linux-x86_64/egg/psignifit
creating build/bdist.linux-x86_64/egg/psignifit/demos
copying build/lib/psignifit/demos/demo_001.py -> build/bdist.linux-x86_64/egg/psignifit/demos
copying build/lib/psignifit/demos/demo_002.py -> build/bdist.linux-x86_64/egg/psignifit/demos
copying build/lib/psignifit/demos/demo_003.py -> build/bdist.linux-x86_64/egg/psignifit/demos
copying build/lib/psignifit/demos/demo_004.py -> build/bdist.linux-x86_64/egg/psignifit/demos
copying build/lib/psignifit/demos/demo_005.py -> build/bdist.linux-x86_64/egg/psignifit/demos
copying build/lib/psignifit/demos/demo_006.py -> build/bdist.linux-x86_64/egg/psignifit/demos
copying build/lib/psignifit/demos/__init__.py -> build/bdist.linux-x86_64/egg/psignifit/demos
copying build/lib/psignifit/getConfRegion.py -> build/bdist.linux-x86_64/egg/psignifit
copying build/lib/psignifit/getSeed.py -> build/bdist.linux-x86_64/egg/psignifit
copying build/lib/psignifit/getSigmoidHandle.py -> build/bdist.linux-x86_64/egg/psignifit
copying build/lib/psignifit/getWeights.py -> build/bdist.linux-x86_64/egg/psignifit
copying build/lib/psignifit/gridSetting.py -> build/bdist.linux-x86_64/egg/psignifit
copying build/lib/psignifit/likelihood.py -> build/bdist.linux-x86_64/egg/psignifit
copying build/lib/psignifit/marginalize.py -> build/bdist.linux-x86_64/egg/psignifit
copying build/lib/psignifit/poolData.py -> build/bdist.linux-x86_64/egg/psignifit
copying build/lib/psignifit/priors.py -> build/bdist.linux-x86_64/egg/psignifit
copying build/lib/psignifit/psignifit.py -> build/bdist.linux-x86_64/egg/psignifit
copying build/lib/psignifit/psigniplot.py -> build/bdist.linux-x86_64/egg/psignifit
creating build/bdist.linux-x86_64/egg/psignifit/tests
copying build/lib/psignifit/tests/test_basic.py -> build/bdist.linux-x86_64/egg/psignifit/tests
copying build/lib/psignifit/tests/test_CItest.py -> build/bdist.linux-x86_64/egg/psignifit/tests
copying build/lib/psignifit/tests/__init__.py -> build/bdist.linux-x86_64/egg/psignifit/tests
copying build/lib/psignifit/utils.py -> build/bdist.linux-x86_64/egg/psignifit
copying build/lib/psignifit/__init__.py -> build/bdist.linux-x86_64/egg/psignifit
byte-compiling build/bdist.linux-x86_64/egg/psignifit/borders.py to borders.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/demos/demo_001.py to demo_001.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/demos/demo_002.py to demo_002.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/demos/demo_003.py to demo_003.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/demos/demo_004.py to demo_004.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/demos/demo_005.py to demo_005.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/demos/demo_006.py to demo_006.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/demos/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/getConfRegion.py to getConfRegion.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/getSeed.py to getSeed.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/getSigmoidHandle.py to getSigmoidHandle.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/getWeights.py to getWeights.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/gridSetting.py to gridSetting.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/likelihood.py to likelihood.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/marginalize.py to marginalize.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/poolData.py to poolData.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/priors.py to priors.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/psignifit.py to psignifit.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/psigniplot.py to psigniplot.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/tests/test_basic.py to test_basic.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/tests/test_CItest.py to test_CItest.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/tests/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/utils.py to utils.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/psignifit/__init__.py to __init__.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying psignifit.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying psignifit.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying psignifit.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying psignifit.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying psignifit.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
psignifit.__pycache__.__init__.cpython-34: module references __file__
creating 'dist/psignifit-0.1-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing psignifit-0.1-py3.4.egg
removing '/usr/local/lib/python3.4/dist-packages/psignifit-0.1-py3.4.egg' (and everything under it)
creating /usr/local/lib/python3.4/dist-packages/psignifit-0.1-py3.4.egg
Extracting psignifit-0.1-py3.4.egg to /usr/local/lib/python3.4/dist-packages
psignifit 0.1 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.4/dist-packages/psignifit-0.1-py3.4.egg
Processing dependencies for psignifit==0.1
Searching for pytest
Reading https://pypi.python.org/simple/pytest/
Download error on https://pypi.python.org/simple/pytest/: hostname 'proxy.iiit.ac.in' doesn't match either of 'www.python.org', 'docs.python.org', 'bugs.python.org', 'wiki.python.org', 'hg.python.org', 'mail.python.org', 'pypi.python.org', 'packaging.python.org', 'login.python.org', 'discuss.python.org', 'us.pycon.org', 'pypi.io', 'docs.pypi.io', 'pypi.org', 'docs.pypi.org', 'donate.pypi.org', 'devguide.python.org', 'www.bugs.python.org', 'python.org' -- Some packages may not be found!
Couldn't find index page for 'pytest' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: hostname 'proxy.iiit.ac.in' doesn't match either of 'www.python.org', 'docs.python.org', 'bugs.python.org', 'wiki.python.org', 'hg.python.org', 'mail.python.org', 'pypi.python.org', 'packaging.python.org', 'login.python.org', 'discuss.python.org', 'us.pycon.org', 'pypi.io', 'docs.pypi.io', 'pypi.org', 'docs.pypi.org', 'donate.pypi.org', 'devguide.python.org', 'www.bugs.python.org', 'python.org' -- Some packages may not be found!
No local packages or download links found for pytest
error: Could not find suitable distribution for Requirement.parse('pytest')`


How do I solve this now ??

**Comment by otizonaizit** [comment]
> Most significant part of the error message being `error: Could not find suitable distribution for Requirement.parse('pytest')`

No, this is not the most significant part. The most significant part is the following:
 
> Searching for pytest
> Reading https://pypi.python.org/simple/pytest/
> Download error on https://pypi.python.org/simple/pytest/: hostname 'proxy.iiit.ac.in' doesn't match either of 'www.python.org', 'docs.python.org', 'bugs.python.org', 'wiki.python.org', 'hg.python.org', 'mail.python.org', 'pypi.python.org', 'packaging.python.org', 'login.python.org', 'discuss.python.org', 'us.pycon.org', 'pypi.io', 'docs.pypi.io', 'pypi.org', 'docs.pypi.org', 'donate.pypi.org', 'devguide.python.org', 'www.bugs.python.org', 'python.org' -- Some packages may not be found!
> Couldn't find index page for 'pytest' (maybe misspelled?)

Which clearly indicates that you are behind an http proxy (`proxy.iiit.ac.in`) which is intercepting pip's attempts to connect to the internet. You may want to use the `--proxy` option to the `pip` command. How exactly that may works depends on your setup.

**Comment by Openbro** [comment]
I get that clearly but the issue is the package installation `which in this case is pytest` is invoked when i run setup.py.

How do i exempt this package from the rest to use proxy?

Also, all the other packages work fine in this. using `--proxy ` can help how ??

**Comment by otizonaizit** [comment]
@Openbro : there is only so much we can do remotely to help you.

Your setup is broken, and it will fail with other packages too. psignifit depends additionaly on scipy and matplotlib. It can be that you don't get the error for these two because you have them already installed in the system or in the virtualenv you are using.

`--proxy` will instruct pip to use your https proxy to get to the internet instead of trying directly.

**Comment by Openbro** [comment]
Okay, thanks for your help.

I will sort it out on my end.

Cheers
