### ISSUE TITLE
Impossible to pass custom axis handle to plotMarginal method

### ISSUE THREAD

**Issue by Fperdreau** [wichmann-lab/python-psignifit#21]
Hi,

I have been playing around with the Python version of psignifit and I realized that custom axis handles passed as argument to the `plotMarginal` method does not work as expected. My use case was to plot the marginal posterior density of each parameter in a grid plot:

```python
parameters_index = {'alpha': 0, 'beta': 1, 'gamma': 2, 'lambda': 3}

fig, axes = plt.subplots(nrows=2, ncols=2)
axes = axes.flatten()

for parameter_label, parameter_index in parameters_index.items():
    g = ps.psigniplot.plotMarginal(res, 
                                   dim=parameter_index, 
                                   axisHandle=axes[parameter_index],
                                   showImediate=False)
plt.tight_layout()
```

Using the code above, all the plots are rendered in the last axis (`subplot(1,1)`) only.

Looking at the code of  `plotMarginal`, it appears that `axisHandle` is set to `None` on the first line of the method and thus the custom argument is ignored:

https://github.com/wichmann-lab/python-psignifit/blob/bbe328832d7c6fe5998efa7eb44af88db559c06c/psignifit/psigniplot.py#L260

Removing this line fixes the issue.

I created a fix-branch on my fork, so I can prepare a PR if you're interested.

**Comment by HeikoSchuett** [comment]
Thank you for finding this one! Quite clearly this is a bug. If you would like to be credited for it in the contribution pages, please go ahead and start a pull request. Otherwise I am happy to start one myself.

**Comment by Fperdreau** [comment]
Sorry for the late reply. I created the PR.
