### ISSUE TITLE
Deploy docs 

### ISSUE THREAD

**Issue by dekuenstle** [wichmann-lab/python-psignifit#39]
The documentation (#36 ) should be automatically build and deployed. (see #29 )

**Comment by dekuenstle** [comment]
@otizonaizit If we stick to readthedocs, this issue should be rather simple. 
Readthedocs provides an URL, which can be added as a Webhook in the project settings .
More details here: https://docs.readthedocs.io/en/stable/webhooks.html

Either I send you the URL so you can add the webhook, or you'll have to give me access rights in this project to do it myself.

**Comment by otizonaizit** [comment]
you are admin now and should be able to manage hooks on your own!

**Comment by dekuenstle** [comment]
Thank you! The webhook is now up and running.
