### ISSUE TITLE
Small typo in basic usage page in wiki

### ISSUE THREAD

**Issue by vinzenz-mimi** [wichmann-lab/python-psignifit#5]
https://github.com/wichmann-lab/python-psignifit/wiki/Basic-Usage
In line 47 it says
>    result['conf_intervals']

but it should be
>    result['conf_Intervals']

Thanks and best wishes to Felix!

**Comment by HeikoSchuett** [comment]
Thanks for finding this typo!
I just changed it.

And I will send your greetings to Felix!
