### ISSUE TITLE
allowing data at stimulus level 0 for log space sigmoids

### ISSUE THREAD

**Issue by HeikoSchuett** [wichmann-lab/python-psignifit#52]
I got a request recently to make it possible to use data at stimulus level 0 to constrain the guess rate for a yes/no detection paradigm. It was relatively easy to allow this in the MATLAB version, so I implemented it there.

It would be great if this change could be made in the python version as well. 

I did not simply implement this myself for now,  as I am not sure when a good time would be relative to the ongoing refactoring work.

**Comment by dekuenstle** [comment]
Thanks Heiko, I will consider this feature during refactoring.

**Comment by dekuenstle** [comment]
Hey @HeikoSchuett ,
is this close to the fix in the matlab version? 
Thanks
David

**Comment by pberkes** [comment]
This is only necessary in logarithmic space, and the option is not available anymore. Users will have to deal with this manually when transforming the stimulus levels
