### ISSUE TITLE
Using `getStandardParameters.py`

### ISSUE THREAD

**Issue by elleobrien** [wichmann-lab/python-psignifit#55]
I see that this function is available, but it does seem to be loaded as a module in `psignifit.py` so it isn't callable from the `psignfit` module. Is this intentional?

**Comment by dekuenstle** [comment]
In the current API, you would have to import this function from a separate module:
```
from psignifit.getStandardParameters import getStandardParameters
``` 

Please notice, that we are working on a more "pythonic" API at the moment. See [this project](https://github.com/wichmann-lab/python-psignifit/projects/1) if you are curious.
