### ISSUE TITLE
ps.plot should be ps.psigniplot in basic usage page in wiki

### ISSUE THREAD

**Issue by vinzenz-mimi** [wichmann-lab/python-psignifit#6]
https://github.com/wichmann-lab/python-psignifit/wiki/Basic-Usage
l.61 currently is
> ps.plot.plotPsych(result)

but should be
> ps.psigniplot.plotPsych(result)

**Comment by HeikoSchuett** [comment]
Hi Vini,
indeed this was correct until the restructuring and is now wrong everywhere. I just fixed it in the demo code and will now look through the help. 

Thank you again for testing!
