### ISSUE TITLE
Setting borders breaks when fixing multiple parameters

### ISSUE THREAD

**Issue by vinzenz-mimi** [wichmann-lab/python-psignifit#7]
with 
`options['fixedPars'] = np.ones([5,1])*np.nan`
`options['fixedPars'][2] = 0   # lambda, the upper asymptote/lapse rate`
`options['fixedPars'][3] = .5   # gamma, the lower asymptote/guess rate`
`options['fixedPars'][4] = 0   # eta, overdispersion parameter`

I get this:
> ~/anaconda/lib/python3.6/site-packages/psignifit/psignifit.py in psignifit(data, optionsIn)

`    258     if (border_idx[0].size > 0):`
`--> 259         options['borders'][border_idx[0],0] = options['fixedPars'][border_idx[0]]`
`    260            options['borders'][border_idx[0],1] = options['fixedPars'][border_idx[0]]`

> ValueError: shape mismatch: value array of shape (3,1) could not be broadcast to indexing result of shape (3,)

This happens as soon as you attempt to fix more than 1 parameter. 

I got it to work with modifying psignifit.py at:
`  259         options['borders'][border_idx[0],0:1] = options['fixedPars'][border_idx[0]]`
`  260         options['borders'][border_idx[0],1:2] = options['fixedPars'][border_idx[0]]`

I'm running
`print (sys.version)`
> 3.6.3 |Anaconda custom (64-bit)| (default, Nov  3 2017, 12:34:11) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

and 
`np.__version__`
> '1.13.3'

**Comment by HeikoSchuett** [comment]
Hi! 
I checked this and fixed it slightly differently with proper indexing as it is intended by np.where (I think)

Also: Apologies for leaving so many bugs in.

**Comment by vinzenz-mimi** [comment]
Thanks for your quick reply and fix. See my comment in the corresponding commit. 
https://github.com/wichmann-lab/python-psignifit/commit/e5285a6b20aa2b63adbf469f9570445611148771#diff-6ebc499ea39342ee88874021e85b6190R259
Could you have another look at it? Have you actually tested it?

**Comment by HeikoSchuett** [comment]
Hi Vinzenz,
I had another look and while checking these got quite annoyed with using a 2D array for fixedPars. I changed this now and introduced a proper tests that this works. Now at least psignifit does actually fix the two parameters I fixed correctly (see fixedPars branch & Pull request)

I hope with this I am actually done with these problems for now.
