### ISSUE TITLE
Backport fixes from master branch

### ISSUE THREAD

**Issue by otizonaizit** [wichmann-lab/python-psignifit#89]
List of commits in the master branch since refactor-api branched out, generated with `git log --no-merges --format=%H master ^refactor-api | tac`:

- [x] aa98951104bae64f431f465b2c2692696f33a9e8 : this commit introduces a getParameters function that converts a sigmoid which is parametrized with threshold and width to the standard parametrization from old literature, which depends on the sigmoid used. It doesn't seem particularly urgent, so no need to backport it
- [x] 55853c672e7367e9a82cb91a962b1834d732ffec : this commit makes plotting non blocking. It is not relevant for us, because we are not going to call `plt.show` directly anyway
- [x] d7d207cd33523f603f6464ea3da11bd9c4d90873 : this commit fixes a bug when the estimate type is `mean`. But the default estimate type is `MAP` and in the refactored version we don't really support any other estimate type, so it is not relevant: see #92
- [x] ff7e0c9a0b4ad5556c712f1fccbce62e70f1c764 : this commit fixes a bug in the treatment of sigmoid names, which we don't have in the refactor version
- [x] a3a812a4ef2babb77b6c4408b58a6552cadcf2c0 : this commit fixes a bug in the logistic sigmoid, which had been fixed already in refactor-api 
- [x] dd39446c121ecfb63a8c36d847a0ec26b21ba0a9 : this commit fixes a bug in computing the marginal distribution, which is not present in refactor-api
- [x] 68d54aa35951930de73f5644b7bdf4c97e0f8953 : this commit introduces CI testing. We are tracking this on #85 

Tick out the ones that have been backported.

**Comment by guillermoaguilar** [comment]
This one also, related to issue #70 and PR #71

3c3c24

**Comment by pberkes** [comment]
all fixed
