### ISSUE TITLE
`posterior_mass` attribute in `Results` object is not used and should go

### ISSUE THREAD

**Issue by otizonaizit** [wichmann-lab/python-psignifit#93]

**Comment by otizonaizit** [comment]
we can keep it if we introduce some kind of `debug` mode, which would allow us to also create 2-D plots to visualize the 5-d posterior distribution

**Comment by dekuenstle** [comment]
The `posterior_mass` is required to call `plot_2D_margin`. Do you think this plotting function is not needed and should go to?
